### ISSUE TITLE
Move rubric suggestions out from behind account-wall

### ISSUE THREAD

**Issue by yohanmishkin** [Politiwatch/privacyspy#1]
Super exciting project! Thanks so much for the idea and the work so far.

Currently people wanting to share potential suggestions to the rubric are directed to an account-wall per https://privacyspy.org/about/#rubric ("please feel free to [create a suggestion](https://privacyspy.org/create-suggestion/)").

Adopting an RFC process like that of the [Rust](https://github.com/rust-lang/rfcs) or [Ember.js](https://github.com/emberjs/rfcs/) communities' could be a great way to solicit more discourse and give the rubric better flexibility as the privacy landscape changes.

** Apologies if there already is a place in the open for discussing and suggesting changes to the rubric.

**Comment by milesmcc** [comment]
It's happening in the rewrite! We're now going to be using GitHub to track contributions and suggestions. Thanks for bringing this up.
