### ISSUE TITLE
Change CI bot logo

### ISSUE THREAD

**Issue by doamatto** [Politiwatch/privacyspy#104]
**What do you want added to PrivacySpy?**
The current CI bot's logo looks fine on [the app marketplace page](https://github.com/apps/privacyspy-bot), but is barely recognisable on dark theme.

**Have you considered implementing this addition yourself and submitting a pull request?**
There is the old logo on Product Hunt that could be used, that or simply adding a white background to the image

**Additional context**
![image](https://user-images.githubusercontent.com/30969346/123467182-1004c400-d5a5-11eb-8560-c168b886c4b8.png)

**Comment by ibarakaiev** [comment]
@milesmcc since you built the bot, could you look into it?

**Comment by milesmcc** [comment]
Changed to have a white background (I think).
