### ISSUE TITLE
Grammarly - Product Request

### ISSUE THREAD

**Issue by pcgamer31098** [Politiwatch/privacyspy#111]
**What's the product you'd like PrivacySpy to add?**
I want Grammarly added to PrivacySpy because...it is a popular service with questionable privacy practices.

**Where is the product's privacy policy? (Give a URL.)**
https://www.grammarly.com/privacy-policy

**Have you considered adding this product yourself?**
(PrivacySpy is an open project, so you can contribute! If you're not feeling up to it, though, that's alright.)

**Comment by milesmcc** [comment]
This would be a great product addition! I'll leave this open for anyone who wants to take this on.

**Comment by doamatto** [comment]
Can be closed as #113 has been merged.
