### ISSUE TITLE
Old pending contributions gone?

### ISSUE THREAD

**Issue by doamatto** [Politiwatch/privacyspy#13]
As you may (or may not) be aware, I contributed a lot of things to PrivacySpy, a number of which that were pending for approval to be added. Do you guys still have a copy of those TOMLs or do I have to redo all of them? I wouldn't exactly mind if I had to, but it would be a pain as it's ~150 products with the old GUI for making these gone

**Comment by milesmcc** [comment]
Check out PR #12 — we’re on it! All your files are pending a merge.

We launched the new version with the products that needed no edits (including some of yours!), and we’re in the process of bringing in the rest.

**Comment by doamatto** [comment]
Alright; thanks for letting me know 😄

**Comment by milesmcc** [comment]
By the way @doamatto, feel free to submit PRs directly to this repo going forward. Check out the contributing guide if you haven’t already — it should explain everything, and if anything is unclear, lmk.

**Comment by doamatto** [comment]
Yea I saw the new contribution guidelines and other bits. I'll be sure to let you guys know. Thanks for being awesome :)
