### ISSUE TITLE
Bring back the GUI generator

### ISSUE THREAD

**Issue by doamatto** [Politiwatch/privacyspy#15]
**What do you want added to PrivacySpy?**
Basically the title; at the very least, I would like to have it make the TOML files for me. If it's not planned or anything like that, I'll just make a separate tool for it [here](https://github.com/doamatto/privacyspy-gen).

**Have you considered implementing this addition yourself and submitting a pull request?**
Nope. It wouldn't exactly be a simple implementation

**Comment by milesmcc** [comment]
This is something we're planning on building relatively soon (in a different repository). It'd be a site that allows you to edit the policy in a graphical interface, then export to a TOML file for easy PR creation. (We'd also allow easy imports of existing TOML files.)

**Comment by doamatto** [comment]
Good to hear; I'm open to helping where I can :)

24 Jun 2020, 20:23 by notifications@github.com:

**Comment by milesmcc** [comment]
Just want to revise my original comment a bit: if this is something you want to build, do it—it’s not on our short term roadmap, but is something we’re hoping to have in the future. Even if you end up building it just for your personal use, we’d be happy to link to it from our “contribute” page if you put it up on GitHub Pages or Netlify or something.

**Comment by doamatto** [comment]
Mkay; I'll start working on it in my free-time. Would the legacy repo have the old contributions GUI (it would be nice to keep the same design language imo)?

25 Jun 2020, 06:14 by notifications@github.com:
