### ISSUE TITLE
Add Skiff

### ISSUE THREAD

**Issue by Just-a-random-person123** [Politiwatch/privacyspy#177]
**What's the product you'd like PrivacySpy to add?**
I want Skiff added to PrivacySpy because they claim to be a very privacy-focused company and I want people to be able to easily see if that is right without having to read their lengthy official privacy policy and comparing it to the "Plain English" version

**Where is the product's privacy policy? (Give a URL.)**
https://app.skiff.com/docs/db93c237-84c2-4b2b-9588-19a7cd2cd45a#tyGksN9rkqbo2uGYASxsA6HVLjUoly/wTYK8tncTto8= (official)
https://skiff.com/annotated-privacy-policy (annotated/plain english)

**Have you considered adding this product yourself?**
Yes, but I have little to no experience with Git and I would not know where to start with TOML and summarizing the privacy policy

**Comment by doamatto** [comment]
Closing this since Skiff is being merged into Notion and shut down.
