### ISSUE TITLE
Add ente - private cloud for your photos & videos

### ISSUE THREAD

**Issue by iAnonymous3000** [Politiwatch/privacyspy#185]
**What's the product you'd like PrivacySpy to add?**

I want Ente (https://ente.io/) added to PrivacySpy because it is a privacy-focused, end-to-end encrypted photo storage and backup app that serves as a secure alternative to apps like Google Photos or iCloud Photos. Its key features include:

- Full end-to-end encryption, ensuring only the user can access their photos
- Open source clients, allowing verification of the privacy claims
- Durable storage with 3 copies of data stored in 3 clouds for reliability 
- Support for viewing, sharing, and organizing photos across platforms (iOS, Android, web, desktop)
- Affordable pricing plans that can be shared with family at no extra cost
- Responsive development team and positive user reviews

Ente has been audited by reputable cryptographers and seems to be delivering on its privacy promises while providing a smooth user experience. I believe it would be an excellent addition to PrivacySpy's product reviews.

**Where is the product's privacy policy? (Give a URL.)**

https://ente.io/privacy

**Have you considered adding this product yourself?**

I appreciate that PrivacySpy is an open project and welcome contributions. However, as I am not currently familiar with the process of adding products or the rubric used for scoring, I thought it would be best to submit this request for the team's consideration first. If there is documentation on how to properly evaluate and add products, I would be happy to explore contributing the Ente review myself. Please let me know if you have any guidance or resources to point me in the right direction. Thank you!

**Comment by doamatto** [comment]
You can see how to add a product [here](https://privacyspy.org/contribute/#submitting). If you need help, feel free to let me know ; otherwise, I might have a chance to add this myself some time later this month.
