### ISSUE TITLE
Adjust behavorial marketing score for existence of differential privacy implementations

### ISSUE THREAD

**Issue by yohanmishkin** [Politiwatch/privacyspy#2]
[Differential privacy](https://en.wikipedia.org/wiki/Differential_privacy) provides a way to analyze large data-sets without violating the privacy of individuals. 

Adjusting the scoring of the rubric's question "Does the policy allow personally-targeted or behavioral marketing?" for a company's use of differential privacy might make sense.

**Comment by doamatto** [comment]
This has since been fixed in (at the latest) 816b35e. This can be closed

cc: @milesmcc @ibarakaiev
