### ISSUE TITLE
Dark theme?

### ISSUE THREAD

**Issue by doamatto** [Politiwatch/privacyspy#3]
Basically the title; but will the redesign come with a dark theme? I'm fine with making a PR to add it myself, if needed

**Comment by milesmcc** [comment]
Unfortunately, this isn't something we're considering. I just don't think we have the resources to maintain two versions of our stylesheets. For what it's worth, the auto dark mode extension works quite well on PrivacySpy!

**Comment by doamatto** [comment]
Afaik you wouldn't need two separate sheets. For instance, if you mention a font needs to be black, right after you can use `@media(prefers-color-scheme: dark){}` right after to declare the light version. You'd only have to add supplements for things that would be directly affected, too. I'd be fine with doing upkeeping if needed.

**Comment by milesmcc** [comment]
I should probably clarify my comment above: we don’t technically have _any_ stylesheets—we use Tailwind CSS. I really think that keeping the source code slim is worthwhile here :/

**Comment by doamatto** [comment]
Gotcha; I haven't used Tailwind before so I can't provide any insight there. If I find anything out in the future, I'll let you guys know then

**Comment by doamatto** [comment]
We could re-open this as with Tailwind 2.0 [the dark variant](https://tailwindcss.com/docs/dark-mode) was added and allows you to use it just like other states utilities (eg. `hover:`, `focus:`, `dark:`). I'd be fine with helping out with doing this up, as well.
