### ISSUE TITLE
Suggestion: Add more data for each service in the PrivacySpy API

### ISSUE THREAD

**Issue by Tetracyl** [Politiwatch/privacyspy#37]
Would it be possible to have the data from the .toml files available for each service in the API? 
The only data that is available right now is the score, name, and description. I'd love to see other data being added such as sources, rubric, and citations.

**Comment by milesmcc** [comment]
Yeah, this is something I'd like to add. Is there a particular use-case you have in mind that we could optimize for?

**Comment by Tetracyl** [comment]
Recently, I've developed an app using the PrivacySpy API, however, it's quite limited by the data on the API. The PrivacySpy browser extension is also quite limited due to the data on the API.

**Comment by doamatto** [comment]
This issue pertains more to the API than the website, so I'd recommend cross-posting to [Politiwatch/PrivacySpy-API](https://github.com/Politiwatch/PrivacySpy-API) and closing this issue to have it in the right home.

**Comment by milesmcc** [comment]
That repository is the API for the website prior to the redesign; as part of the redesign last summer, we merged everything in here. We should probably archive that repository to keep things more clear!

Point is only that I think this is the right place for the issue for now. But thanks for being proactive, @doamatto!
