### ISSUE TITLE
Option for light icon

### ISSUE THREAD

**Issue by Tauin-zz** [Politiwatch/privacyspy#38]
**What do you want added to PrivacySpy?**
having a option to choose between a light or dark icon could help with visibility for people using dark themes in firefox/chrome 
**Have you considered implementing this addition yourself and submitting a pull request?**
I could probably easily make the icon, but how to add the option im not sure

**Comment by Tauin** [comment]
[https://raw.githubusercontent.com/Tauin/etcmisc/master/privacyspylight.svg](url) not the best, but it'll work

**Comment by ibarakaiev** [comment]
Hi @Tauin, thanks for opening this issue. Our website's favicon and browser extension's icon already include a dark-theme variant that is selected based on your browser's theme (see `<styles>` at https://github.com/Politiwatch/privacyspy/blob/master/src/static/img/fingerprint-icon.svg). Could you clarify what do you mean by an option to select it and what icon you are referring to, so I can be more helpful?

**Comment by Tauin** [comment]
>  browser extension's icon already include a dark-theme variant that is selected based on your browser's theme

if you do its not working unfortunately, heres my browser using the "matte black" theme:
![Screenshot 2020-08-16 015904](https://user-images.githubusercontent.com/59283710/90316308-d0933300-df10-11ea-9487-34d35d6629a4.png)
gets even worse if you move it up into the tab section:
![Screenshot 2020-08-16 020009](https://user-images.githubusercontent.com/59283710/90316312-d2f58d00-df10-11ea-8bf1-a7d8bc9659e0.png)

**Comment by doamatto** [comment]
@Tauin This issue should be made in [Politiwatch/PrivacySpy-Extension](https://github.com/Politiwatch/PrivacySpy-Extension) instead, as that repo focuses on the development of the browser extension

**Comment by doamatto** [comment]
This is fixed in v2 of the browser extension. This can be closed.

cc @milesmcc @ibarakaiev
