### ISSUE TITLE
Archive GitHub action dependencies

### ISSUE THREAD

**Issue by doamatto** [Politiwatch/privacyspy#45]
**What do you want added to PrivacySpy?**
To reduce the time for using GitHub actions, we can archive and re-use the dependencies and have them be refreshed whenever there's a new update.

**Have you considered implementing this addition yourself and submitting a pull request?** I wanted to run it by the team first.

**Additional context** I've set it up in the past before; [here's the documentation regardless](https://github.com/actions/cache)

**Comment by ibarakaiev** [comment]
@milesmcc what do you think? Sounds good to me (I don't see downsides) but I didn't set up Github Actions for PrivacySpy so would love to hear what you think first.

**Comment by milesmcc** [comment]
I say go for it. I haven't setup caching before and we don't have enough activity on the repo to make it _necessary_, but feel free to submit a PR that does this!
