### ISSUE TITLE
Add commas to lists of products

### ISSUE THREAD

**Issue by doamatto** [Politiwatch/privacyspy#51]
**What's the issue? Describe the problem below.**
When a product with several "sub-products" is listed, it appears as one "blob" as the screenshot shows

**What did you expect to be the case instead?**
I expected to be a clear seperation to prevent confusion between services.

**Screenshots?**
![image](https://user-images.githubusercontent.com/30969346/102526899-31628180-4051-11eb-83b0-abaf2595da92.png)

**Additional context?** N/A

**Comment by ibarakaiev** [comment]
Good catch. I will get to this issue sometime this week.

**Comment by doamatto** [comment]
Resolved in #78.
