### ISSUE TITLE
WhatsApp: data breaches (inconsistency) and EEA privacy policy

### ISSUE THREAD

**Issue by erotavlasme** [Politiwatch/privacyspy#88]
**What's the issue? Describe the problem below.**
1) Data breach notification policy is not defined by WhatsApp privacy policy (both version [EEA](https://www.whatsapp.com/legal/privacy-policy-eea) and the [rest of the world](https://www.whatsapp.com/legal/privacy-policy)).
2) The review is based on EEA privacy policy which applies to EU only.

**What did you expect to be the case instead?**
1) Mark should be aligned with those of other services (telegram, signal, wire) which get 0 in case of missing data breach notification policy `[rubric.data-breaches]`.
2) Use rest of the world privacy policy which is less protective.

**Comment by doamatto** [comment]
I think the best course of action in this case is to seperate it into `Whatsapp` and `Whatsapp EEA`, where the EEA is meant for those who reside in the EEA, and the other being for the "rest of the world" policy. Feel free to make a PR to do this up.

**Comment by milesmcc** [comment]
> I think the best course of action in this case is to seperate it into `Whatsapp` and `Whatsapp EEA`, where the EEA is meant for those who reside in the EEA, and the other being for the "rest of the world" policy. Feel free to make a PR to do this up.

Yeah, I agree. This is a tough one but splitting into EEA/non-EEA is probably the best way forward.

**Comment by erotavlasme** [comment]
I agree with both. In the meantime, I corrected rubric.data-breaches https://github.com/Politiwatch/privacyspy/pull/93. I hope to have time to review the non EEA privacy policy.

**Comment by milesmcc** [comment]
Perfect! I am going to close this issue in the meantime because I think the primary issue is solved. It'd be great to have an EEA version of the policy, though I don't think it's _critically_ important — so I totally get it if you'd prefer to review a different policy instead :)
