### ISSUE TITLE
ProtonVPN: security audit and details, incorrect revision-notify

### ISSUE THREAD

**Issue by erotavlasme** [Politiwatch/privacyspy#90]
**What's the issue? Describe the problem below.**
1) ProtonVPNl has received an independent audit, though these are not mentioned in the policy as their official security measure. Some security details are missing.
2) [rubric.revision-notify]. The score is incorrect.

**What did you expect to be the case instead?**
1) All ProtonVPN apps are now [open source and audited](https://protonvpn.com/blog/open-source). "For users with heightened security needs, it is possible to optionally i) enable 2FA on account access ii) enable login history so that suspicious login attempts can be tracked iii) remove the linked recovery email iv) pay anonymously with cash or bitcoin."
2) [rubric.revision-notify]=yes. "The Company reserves the right to periodically review and change this Policy, and will notify users who have enabled the notification preference about any change."

**Comment by doamatto** [comment]
The quote for your second point doesn't really relate to auditing or that it's open-source. However, feel free to make a PR correcting the issues you mentioned.

**Comment by milesmcc** [comment]
I think you're right, @erotavlasme. Feel free to submit a PR that makes this change.

**Comment by erotavlasme** [comment]
https://github.com/Politiwatch/privacyspy/pull/92
