### ISSUE TITLE
Rating of PrivacySpy could be better

### ISSUE THREAD

**Issue by lem0n4id** [Politiwatch/privacyspy#94]
**What's the issue? Describe the problem below.**
Under the [Transparency tab of PrivacySpy](https://privacyspy.org/product/privacyspy/), under the question 'Is the policy's history made available?', 
The answer is written 'Only the date it was last modified' which gives it a score of only 3/5. 
Check the screenshots attached.

**What did you expect to be the case instead?**
as the note states 

> While one could check the full history on GitHub, only the last modified date is listed on the page.

So changes that could be added are-

1. change it into 'Yes, with revisions or a changelog'
2. change the note to 'full history can be viewed on GitHub' or something similar that makes it clear that it is available. 

**Screenshots?**
![image](https://user-images.githubusercontent.com/61219881/122249636-a28ece80-cee6-11eb-97e5-f5a62d1b81d2.png)

**Comment by milesmcc** [comment]
You're totally right — the history is available on GitHub. I've always been a bit hesitant to edit our own ratings — I worry it'd look a bit strange if we had a perfect 10/10, as judged by yours truly — but please feel free to submit a PR for this. I'd really appreciate it!

**Comment by doamatto** [comment]
Made a PR to rig.. I mean.. update the PrivacySpy score @milesmcc. Seems the policy was back from when there were user signups.

**Comment by milesmcc** [comment]
Closed in #95!
