### ISSUE TITLE
addition of exceptions

### ISSUE THREAD

**Issue by lem0n4id** [Politiwatch/privacyspy#98]
**What do you want added to PrivacySpy?**
Addition of exceptions in the rubric.

I found this data on tosdr- you can check it out [here](https://edit.tosdr.org/points/13948).

Though the point I have mentioned is debatable, 
I feel like there could be more exceptions that could affect the rating.

The rubric answers a lot of questions but there might be exceptions that any contributor might miss.

I have attached a screenshot as an example

**Have you considered implementing this addition yourself and submitting a pull request?**
Um, I'm not so sure as my web dev skills are not that great, I understand basic js and HTML but nothing more.
I am willing to learn and contribute tho

**Additional context**
![image](https://user-images.githubusercontent.com/61219881/122332807-b6711980-cf54-11eb-8216-9526044b05eb.png)

**Comment by milesmcc** [comment]
Hi! Thanks for the issue report. Exceptions certainly are very important, especially when at the end of the day we do need to reduce everything down to a single score. That being said, perhaps this is a good use case for the notes? Ultimately, all available information should be used to determine the score.

**Comment by doamatto** [comment]
I'd agree with Miles that this would probably be best under the notes section. There are new scores for data deletion in the works (see #97) that are similar to this.
